sudo: true

language: bash

services:
  - docker

env:
  global:
    - DEBIAN_FRONTEND="noninteractive"

jobs:
  include:
    - stage: Build objects 
      if: (NOT (type IN (pull_request)))
      script:
        # build the release contents
        - docker run --rm -it -v $(pwd):/buildout taisun/ubuntu-build:ubuntu-bionic
    - stage: Push release
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(cat shasum)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: 
          - "filesystem.squashfs"
          - "initrd"
          - "vmlinuz"
        skip_cleanup: true
